### ISSUE TITLE
Loot Goblin gets some Real Loot!

### ISSUE THREAD

**Issue by cart** [vanGeck/bevy-jam-2#9]
Hey! So @ramirezmike (winner of Bevy Jam 2) already has some Bevy Merch and has generously decided to "pass down" their winnings (any two items from the Bevy Merch store) to the second place team (you!).

Would you all like to accept the merch? If so, can you discuss amongst yourselves how you would like to split up the loot (two items)?

https://merch.bevyengine.org/

Anyone accepting some (or all) of the loot has a few options:
1. Send me your address (which I will take no record of and promptly forget) and the two items you want and I'll take care of the rest.
2. Order the item(s) you want yourself and I'll send a reimbursement via some reasonable means (negotiable: paypal, venmo, etc)
3. Pass on free stuff :open_mouth:

I wish spring would let me do "full" vouchers / coupons, but thats not an option sadly

**Comment by frederickjjoubert** [comment]
Hi @cart, thanks so much we are absolutely stoked to hear that and really appreciate it. We are discussing amongst ourselves how to divide it up. We would like for two people to each get one item. Our team is also very international with members in the US, Europe, and Japan, are there any shipping restrictions we should be aware of?

Thanks again and also thanks to the other team for passing the loot along. We had a really great experience with the Bevy game jam and can't wait for the next one.

**Comment by cart** [comment]
Spring supports shipping to pretty much everywhere. Glad you enjoyed yourselves!
